# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yumeng/project/master-thesis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yumeng/project/master-thesis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yumeng/project/master-thesis/CMakeFiles /home/yumeng/project/master-thesis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yumeng/project/master-thesis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
<<<<<<< HEAD
# Target rules for targets named gatherpoints

# Build rule for target.
gatherpoints: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gatherpoints
.PHONY : gatherpoints

# fast build rule for target.
gatherpoints/fast:
	$(MAKE) -f CMakeFiles/gatherpoints.dir/build.make CMakeFiles/gatherpoints.dir/build
.PHONY : gatherpoints/fast

gatherpoints.o: gatherpoints.cpp.o

.PHONY : gatherpoints.o

# target to build an object file
gatherpoints.cpp.o:
	$(MAKE) -f CMakeFiles/gatherpoints.dir/build.make CMakeFiles/gatherpoints.dir/gatherpoints.cpp.o
.PHONY : gatherpoints.cpp.o

gatherpoints.i: gatherpoints.cpp.i

.PHONY : gatherpoints.i

# target to preprocess a source file
gatherpoints.cpp.i:
	$(MAKE) -f CMakeFiles/gatherpoints.dir/build.make CMakeFiles/gatherpoints.dir/gatherpoints.cpp.i
.PHONY : gatherpoints.cpp.i

gatherpoints.s: gatherpoints.cpp.s

.PHONY : gatherpoints.s

# target to generate assembly for a file
gatherpoints.cpp.s:
	$(MAKE) -f CMakeFiles/gatherpoints.dir/build.make CMakeFiles/gatherpoints.dir/gatherpoints.cpp.s
.PHONY : gatherpoints.cpp.s
=======
# Target rules for targets named sift_cnn

# Build rule for target.
sift_cnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sift_cnn
.PHONY : sift_cnn

# fast build rule for target.
sift_cnn/fast:
	$(MAKE) -f CMakeFiles/sift_cnn.dir/build.make CMakeFiles/sift_cnn.dir/build
.PHONY : sift_cnn/fast

sift_cnn.o: sift_cnn.cpp.o

.PHONY : sift_cnn.o

# target to build an object file
sift_cnn.cpp.o:
	$(MAKE) -f CMakeFiles/sift_cnn.dir/build.make CMakeFiles/sift_cnn.dir/sift_cnn.cpp.o
.PHONY : sift_cnn.cpp.o

sift_cnn.i: sift_cnn.cpp.i

.PHONY : sift_cnn.i

# target to preprocess a source file
sift_cnn.cpp.i:
	$(MAKE) -f CMakeFiles/sift_cnn.dir/build.make CMakeFiles/sift_cnn.dir/sift_cnn.cpp.i
.PHONY : sift_cnn.cpp.i

sift_cnn.s: sift_cnn.cpp.s

.PHONY : sift_cnn.s

# target to generate assembly for a file
sift_cnn.cpp.s:
	$(MAKE) -f CMakeFiles/sift_cnn.dir/build.make CMakeFiles/sift_cnn.dir/sift_cnn.cpp.s
.PHONY : sift_cnn.cpp.s
>>>>>>> 64494008deeb3605855504907b9870f0ea2e2c38

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
<<<<<<< HEAD
	@echo "... gatherpoints"
	@echo "... gatherpoints.o"
	@echo "... gatherpoints.i"
	@echo "... gatherpoints.s"
=======
	@echo "... rebuild_cache"
	@echo "... sift_cnn"
	@echo "... sift_cnn.o"
	@echo "... sift_cnn.i"
	@echo "... sift_cnn.s"
>>>>>>> 64494008deeb3605855504907b9870f0ea2e2c38
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

